// FIND INDEX OF SMALLEST NUMBER.


// FIND INDEX OF LARGEST NUMBER.


// WAF TO CALCULATE SUM & PRODUCT OFF ALL NUMBERS IN AN ARRAY.


// WAF TO SWAP THE MAX & MIN NUMBER OF AN ARRAY


// WAF TO PRINT ALL THE UNIQUE VALUE IN AN ARRAY


// WAF TO PRINT INTERSECTION OF 2 ARRAY